In [1]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

df = pd.read_csv("data/sales.csv")
df.head()

   user_id button_color  purchase
0        1          Red         0
1        2        Green         0
2        3        Green         0
3        4        Green         0
4        5          Red         0

In [2]:
contingency_table = pd.crosstab(df["button_color"], df["purchase"])
contingency_table

purchase        0   1
button_color
Green         423  74
Red           457  46

In [3]:
chi2, p, dof, expected = chi2_contingency(contingency_table, True)

print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected table:")
print(expected)

Chi-squared statistic: 7.276761963430684
P-value: 0.006985233992323526
Degrees of freedom: 1
Expected table:
[[437.36  59.64]
 [442.64  60.36]]

In [4]:
final_color = "green"
print(final_color)

green