In [ ]:
import pandas as pd

Requirement already satisfied: flaml in /home/norbert/.venvs/ml/lib/python3.12/site-packages (2.3.4)
Requirement already satisfied: NumPy>=1.17 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from flaml) (1.26.4)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: flaml[automl] in /home/norbert/.venvs/ml/lib/python3.12/site-packages (2.3.4)
Requirement already satisfied: NumPy>=1.17 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from flaml[automl]) (1.26.4)
Requirement already satisfied: lightgbm>=2.3.1 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from flaml[automl]) (4.6.0)
Requirement already satisfied: xgboost<3.0.0,>=0.90 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from flaml[automl]) (2.1.4)
Requirement already satisfied: scipy>=1.4.1 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from flaml[automl]) (1.16.2)
Requirement already satisfied: pandas>=1.1.4 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from flaml[automl]) (2.2.3)
Requirement already satisfied: scikit-learn>=1.0.0 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from flaml[automl]) (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from pandas>=1.1.4->flaml[automl]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from pandas>=1.1.4->flaml[automl]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from pandas>=1.1.4->flaml[automl]) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from scikit-learn>=1.0.0->flaml[automl]) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from scikit-learn>=1.0.0->flaml[automl]) (3.6.0)
Requirement already satisfied: nvidia-nccl-cu12 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from xgboost<3.0.0,>=0.90->flaml[automl]) (2.28.7)
Requirement already satisfied: six>=1.5 in /home/norbert/.venvs/ml/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.1.4->flaml[automl]) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
df = pd.read_csv('data/bank-additional-full.csv', na_values='unknown')
df.head()

,age,job,marital,education,default,housing,loan,is_telephone_contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,y
0,56,housemaid,married,basic.4y,no,no,no,yes,may,mon,261,1,999,0,nonexistent,no
1,57,services,married,high.school,NaN,no,no,yes,may,mon,149,1,999,0,nonexistent,no
2,37,services,married,high.school,no,yes,no,yes,may,mon,226,1,999,0,nonexistent,no
3,40,admin.,married,basic.6y,no,no,no,yes,may,mon,151,1,999,0,nonexistent,no
4,56,services,married,high.school,no,no,yes,yes,may,mon,307,1,999,0,nonexistent,no

In [ ]:
categorical_cols = ["month", "education", "day_of_week", "poutcome", "loan", "housing", "default", "job", "marital" , "is_telephone_contact"]
df[categorical_cols] = df[categorical_cols].apply(
    lambda s: s.fillna(s.mode(dropna=True).iloc[0] if not s.mode(dropna=True).empty else s)
)
df.head()
df.isna().sum()

age                     0
job                     0
marital                 0
education               0
default                 0
housing                 0
loan                    0
is_telephone_contact    0
month                   0
day_of_week             0
duration                0
campaign                0
pdays                   0
previous                0
poutcome                0
y                       0
dtype: int64

In [21]:
continuous_cols = ["duration", "age", "pdays", "previous", "campaign"]
binary_cols = ["loan", "housing", "default" , "is_telephone_contact"]
nominal_cols = ["marital" , "job"]
ordinal_cols = ["education", "month", "day_of_week", "poutcome"]

In [ ]:
mapping = {'no': 0,
           'yes' : 1}

binary_df = df[binary_cols]

for i in binary_cols:
    binary_df[i] = binary_df[i].map(mapping)

binary_df.head()

/tmp/ipykernel_69300/281268064.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  binary_df[i] = binary_df[i].map(mapping)
/tmp/ipykernel_69300/281268064.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  binary_df[i] = binary_df[i].map(mapping)
/tmp/ipykernel_69300/281268064.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  binary_df[i] = binary_df[i].map(mapping)
/tmp/ipykernel_69300/281268064.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  binary_df[i] = binary_df[i].map(mapping)

   loan  housing  default  is_telephone_contact
0     0        0        0                     1
1     0        0        0                     1
2     0        1        0                     1
3     0        0        0                     1
4     1        0        0                     1

In [ ]:
nominal_df = df[nominal_cols]
nominal_df = pd.get_dummies(
    nominal_df,
    prefix=nominal_cols,
    prefix_sep='_', 
    dtype=int  
)

nominal_df.head()

,marital_divorced,marital_married,marital_single,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed
0,0,1,0,0,0,0,1,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,1,0,0,0
2,0,1,0,0,0,0,0,0,0,0,1,0,0,0
3,0,1,0,1,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,1,0,0,0

In [ ]:
mapping1 = {
    "illiterate" : 0,
    "basic.4y" : 1,
    "basic.6y" : 2,
    "basic.9y" : 3,
    "high.school" : 4,
    "university.degree" : 5,
    
}

mapping2 ={
    "mon" : 0,
    "tue" : 1,
    "wed" : 2,
    "thu" : 3,
    "fri" : 4,
    "sat" : 5,
    "sun" : 6
}

mapping3 = {
    "jan" : 0,
    "feb" : 1,
    "mar" : 2,
    "apr" : 3,
    "may" : 4,
    "jun" : 5,
    "jul" : 6,
    "aug" : 7,
    "sep" : 8,
    "oct" : 9,
    "nov" : 10,
    "dec" : 11 
}

mapping4 = {
    "failure" : -1,
    "nonexistent" : 0,
    "success" : 1
}

ordinal_df = df[ordinal_cols]
ordinal_df["education"] = ordinal_df["education"].map(mapping1)
ordinal_df["month"] = ordinal_df["month"].map(mapping3)
ordinal_df["day_of_week"] = ordinal_df["day_of_week"].map(mapping2)
ordinal_df["poutcome"] = ordinal_df["poutcome"].map(mapping4)

ordinal_df.head()

/tmp/ipykernel_69300/4254394769.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ordinal_df["education"] = ordinal_df["education"].map(mapping1)
/tmp/ipykernel_69300/4254394769.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ordinal_df["month"] = ordinal_df["month"].map(mapping3)
/tmp/ipykernel_69300/4254394769.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ordinal_df["day_of_week"] = ordinal_df["day_of_week"].map(mapping2)
/tmp/ipykernel_69300/4254394769.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ordinal_df["poutcome"] = ordinal_df["poutcome"].map(mapping4)

   education  month  day_of_week  poutcome
0        1.0      4            0         0
1        4.0      4            0         0
2        4.0      4            0         0
3        2.0      4            0         0
4        4.0      4            0         0