In [1]:
import pandas as pd
from datetime import datetime

In [ ]:
df = pd.read_csv("data/job_posts.csv")
df.head()

,Level,Offers Remote,Publish Time,Salary,Title,Close Time,State,Collaboration Type
0,S,False,2020-04-20 16:52:15,<8MT,توسعه‌دهنده Node.js,2020-06-20 03:00:06,C,FT
1,J,False,2020-02-24 12:55:02,<12MT,توسعه‌دهنده Backend,2020-04-25 03:00:05,C,FT
2,J,True,2020-02-12 13:49:32,<8MT,توسعه‌دهنده C#,2020-04-13 03:00:05,C,FT
3,J,False,2020-08-18 15:46:48,<3MT,توسعه‌دهنده Front-end,2020-08-25 21:51:39,C,PT
4,NaN,False,2017-05-01 20:23:08,NaN,توسعه دهنده #C,2017-06-30 20:23:08,C,NaN

In [22]:
df = df.drop(df[(df['Salary'].isna()) & (df['Level'].isna()) & (df['Collaboration Type'].isna())].index)

In [43]:
df['Salary'] = pd.to_numeric(df['Salary'].str.replace("MT", "").str.replace("<", "").str.replace(">", ""), errors='coerce')
df

,Level,Offers Remote,Publish Time,Salary,Title,Close Time,State,Collaboration Type
0,S,False,2020-04-20 16:52:15,8.0,توسعه‌دهنده Node.js,2020-06-20 03:00:06,C,FT
1,J,False,2020-02-24 12:55:02,12.0,توسعه‌دهنده Backend,2020-04-25 03:00:05,C,FT
2,J,True,2020-02-12 13:49:32,8.0,توسعه‌دهنده C#,2020-04-13 03:00:05,C,FT
3,J,False,2020-08-18 15:46:48,3.0,توسعه‌دهنده Front-end,2020-08-25 21:51:39,C,PT
5,J,False,2020-10-11 12:02:37,NaN,Associate Product Manager,2020-11-08 01:27:52,C,FT
...,...,...,...,...,...,...,...,...
7664,S,False,2021-05-17 10:11:20,NaN,DevOps Engineer,2021-06-27 04:04:50,C,FT
7665,S,False,2021-05-17 09:54:44,NaN,برنامه‌نویس ASP.NET Core,2021-06-27 04:04:50,C,FT
7666,S,False,2021-05-17 09:53:45,NaN,توسعه‌دهنده C++ (qt),2021-06-27 04:04:50,C,FT
7667,S,False,2021-05-17 08:17:06,NaN,کارشناس هوش مصنوعی,2021-06-27 04:04:50,C,FT
7668,S,True,2021-05-15 16:24:36,12.0,توسعه‌دهنده ارشد Front-end,2021-06-27 04:04:50,C,FT

In [ ]:
df['Salary'] = df['Salary'].fillna(df.groupby('Level')['Salary'].transform('mean'))

In [59]:
start_of_corona = datetime.strptime("2020-02-19", "%Y-%m-%d")

In [ ]:
remote_growth = (df[(df['Offers Remote'] == True) & (pd.to_datetime(df['Publish Time']) >= start_of_corona)].shape[0] / df.shape[0]) - (df[(df['Offers Remote'] == True) & (pd.to_datetime(df['Publish Time']) < start_of_corona)].shape[0] / df.shape[0])

In [ ]:
discrete_time = pd.cut(pd.to_datetime(df['Publish Time']).dt.hour, bins=[0, 6, 12, 18, 24], labels=['dawn', 'morning', 'noon', 'night'], right=False).value_counts().sort_values(ascending=False)

In [62]:
keywords = ['machine learning', 'machinelearning', 'داده' , 'data scientist' ,  'datascientist' ,\
        'هوش مصنوعی' ,'پردازش ویدئو' , 'data engineer' , 'dataengineer' ,'بینایی ماشین' , 'یادگیری ماشین' ,\
        'deep learning', 'deeplearning', 'یادگیری عمیق', 'دیتاساینتیست' , 'artificial intelligence' \
        ,'artificialintelligence', 'هوش' , 'data analysis' , 'dataanalysis' , 'پردازش تصویر' , 'شبکه‌های عمیق', 'علم‌داده']

In [ ]:
data_mean = df[df['Title'].str.lower().apply(lambda x: any(keyword in x for keyword in keywords))].groupby('Level')['Salary'].mean().sort_index(ascending=True).astype('float64')