In [ ]:
import datetime 
from datetime import timedelta
import pandas as pd
example_time = datetime.datetime(2021,9,21)
example_time + timedelta(days=10, seconds=50)

datetime.datetime(2021, 10, 1, 0, 0, 50)

In [2]:
example_time - timedelta(days=10, seconds=50)

datetime.datetime(2021, 9, 10, 23, 59, 10)

In [ ]:
df = pd.read_csv("data/notifications_pushe.csv")
df

       action  application_id  interaction_time  notification_id  user_id
0           F               1           4489200               79      665
1           F               1           4489200               79     6280
2           F               1           4388400               78    14774
3           F               1           4410000               78     3152
4           C               1           4410000               72     3633
...       ...             ...               ...              ...      ...
140723      F               0            993600               13    14760
140724      F               0            928800               13     2096
140725      F               0            900000               13    11308
140726      F               0            885600               13     5975
140727      F               0            907200               13    15272

[140728 rows x 5 columns]

In [ ]:
df['date'] = pd.to_datetime(pd.to_datetime("2019-06-01") + pd.to_timedelta(df['interaction_time'].astype(int), unit='s'))
df

,action,application_id,interaction_time,notification_id,user_id,date
0,F,1,4489200,79,665,2019-07-22 23:00:00
1,F,1,4489200,79,6280,2019-07-22 23:00:00
2,F,1,4388400,78,14774,2019-07-21 19:00:00
3,F,1,4410000,78,3152,2019-07-22 01:00:00
4,C,1,4410000,72,3633,2019-07-22 01:00:00
...,...,...,...,...,...,...
140723,F,0,993600,13,14760,2019-06-12 12:00:00
140724,F,0,928800,13,2096,2019-06-11 18:00:00
140725,F,0,900000,13,11308,2019-06-11 10:00:00
140726,F,0,885600,13,5975,2019-06-11 06:00:00
140727,F,0,907200,13,15272,2019-06-11 12:00:00

In [ ]:
tuple_appid_successrate = (int(df.groupby('application_id').apply(lambda group: (group['action'] == 'C').sum() / len(group), include_groups=False).idxmax()), df.groupby('application_id').apply(lambda group: (group['action'] == 'C').sum() / len(group), include_groups=False).max())
tuple_appid_successrate

(1, np.float64(0.18529923416848293))

In [ ]:
tuple_notifid_day = (df.query("action == 'C'").groupby('notification_id').size().div(df.groupby('notification_id').size()).idxmax(), df[df['notification_id'] == df.query("action == 'C'").groupby('notification_id').size().div(df.groupby('notification_id').size()).idxmax()].assign(weekday = pd.to_datetime(df['date']).dt.day_name()).query("action == 'C'").groupby('weekday').size().idxmax())
tuple_notifid_day

(np.int64(79), 'Monday')

In [ ]:
tuple_day_rate = df.groupby(df['date'].dt.day).apply(lambda group: (group['action'] == 'C').sum() / len(group)).idxmax(), df.groupby(df['date'].dt.day).apply(lambda group: (group['action'] == 'C').sum() / len(group)).max()
tuple_day_rate